import 'dart:ui';

import 'package:get/get.dart';

import '../overlays/overlay.dart';

/// A service for showing and closing bottom sheets.
/// Works with [FluorFlowOverlay] instances.
class BottomSheetService {
  /// Returns whether a bottom sheet is currently open.
  bool get isDialogOpen => Get.isBottomSheetOpen ?? false;

  /// Shows a bottom sheet and returns a future with the result.
  /// Use the convenience methods generated by the generator to show a bottom sheet
  /// and return the result in an easy way.
  Future<TResult?> showBottomSheet<TResult, TSheet extends FluorFlowOverlay>(
    TSheet sheet, {
    Color barrierColor = const Color(0x80000000),
    bool fullscreen = false,
    bool draggable = true,
  }) =>
      Get.bottomSheet(
        sheet,
        barrierColor: barrierColor,
        isScrollControlled: fullscreen,
        enableDrag: draggable,
      );

  /// Closes the currently open bottom sheet.
  void closeSheet<T>({bool? confirmed, T? result}) =>
      Get.back(result: (confirmed, result));
}
