name: fluorflow
description: >-
  An MVVM framework for Flutter that allows easy to use MVVM based views in
  Flutter apps. The package shines in combination with the generator (fluorflow_generator)
  to generate extension methods for bottom sheets, routings, dialogs and services.
version: 1.0.3
homepage: https://github.com/smartive/fluorflow
repository: https://github.com/smartive/fluorflow.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  args: ^2.4.2
  code_builder: ^4.9.0
  dart_style: ^2.3.4
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_it: ^7.6.4
  path: ^1.8.3
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
