name: fluorflow
description: An MVVM framework for Flutter to build scalable and maintainable applications.
version: 3.1.0
homepage: https://github.com/smartive/fluorflow
repository: https://github.com/smartive/fluorflow.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  args: ^2.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0
  flutter:
    sdk: flutter
  get_it: ^7.0.0
  path: ^1.0.0
  recase: ^4.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter: null
