name: fluorflow_generator
description: Code Generator for the FluorFlow package.
version: 1.2.1
homepage: https://github.com/smartive/fluorflow
repository: https://github.com/smartive/fluorflow.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.0.0
  build: ^2.0.0
  code_builder: ^4.0.0
  dart_style: ^2.0.0
  fluorflow: ^1.0.0
  glob: ^2.0.0
  path: ^1.0.0
  recase: ^4.0.0
  source_gen: ^1.0.0

dev_dependencies:
  build_test: ^2.2.2
  lints: ^3.0.0
  mockito: ^5.4.4
  test: ^1.25.2
